// This file is auto-generated by ./bin/rails stimulus:install
import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"

eagerLoadControllersFrom("controllers", application)
lazyLoadControllersFrom("controllers", application)