WARD_LIST = [
  { name: "Kitisuru", code: nil, constituency: nil },
  { name: "Parklands/Highridge", code: nil, constituency: nil },
  { name: "Karura", code: nil, constituency: nil },
  { name: "Kangemi", code: nil, constituency: nil },
  { name: "Mountain View", code: nil, constituency: nil },
  { name: "Kilimani", code: nil, constituency: nil },
  { name: "Kawangware", code: nil, constituency: nil },
  { name: "Gatina", code: nil, constituency: nil },
  { name: "Kileleshwa", code: nil, constituency: nil },
  { name: "Kabiro", code: nil, constituency: nil },
  { name: "Mutuini", code: nil, constituency: nil },
  { name: "Ngando", code: nil, constituency: nil },
  { name: "Riruta", code: nil, constituency: nil },
  { name: "Uthiru/Ruthimitu", code: nil, constituency: nil },
  { name: "Waithaka", code: nil, constituency: nil },
  { name: "Karen", code: nil, constituency: nil },
  { name: "Nairobi West", code: nil, constituency: nil },
  { name: "Mugumoini", code: nil, constituency: nil },
  { name: "South C", code: nil, constituency: nil },
  { name: "Nyayo Highrise", code: nil, constituency: nil },
  { name: "Laini Saba", code: nil, constituency: nil },
  { name: "Lindi", code: nil, constituency: nil },
  { name: "Makina", code: nil, constituency: nil },
  { name: "Woodley/Kenyatta Golf", code: nil, constituency: nil },
  { name: "Sarang’ombe", code: nil, constituency: nil },
  { name: "Githurai", code: nil, constituency: nil },
  { name: "Kahawa West", code: nil, constituency: nil },
  { name: "Zimmerman", code: nil, constituency: nil },
  { name: "Roysambu", code: nil, constituency: nil },
  { name: "Kahawa", code: nil, constituency: nil },
  { name: "Clay City", code: nil, constituency: nil },
  { name: "Mwiki", code: nil, constituency: nil },
  { name: "Kasarani", code: nil, constituency: nil },
  { name: "Njiru", code: nil, constituency: nil },
  { name: "Ruai", code: nil, constituency: nil },
  { name: "Baba Dogo", code: nil, constituency: nil },
  { name: "Utalii", code: nil, constituency: nil },
  { name: "Mathare North", code: nil, constituency: nil },
  { name: "Lucky Summer", code: nil, constituency: nil },
  { name: "Korogocho", code: nil, constituency: nil },
  { name: "Imara Daima", code: nil, constituency: nil },
  { name: "Kwa Njenga", code: nil, constituency: nil },
  { name: "Kwa Reuben", code: nil, constituency: nil },
  { name: "Pipeline", code: nil, constituency: nil },
  { name: "Kware", code: nil, constituency: nil },
  { name: "Kariobangi North", code: nil, constituency: nil },
  { name: "Dandora Area I", code: nil, constituency: nil },
  { name: "Dandora Area II", code: nil, constituency: nil },
  { name: "Dandora Area III", code: nil, constituency: nil },
  { name: "Dandora Area IV", code: nil, constituency: nil },
  { name: "Kayole North", code: nil, constituency: nil },
  { name: "Kayole Central", code: nil, constituency: nil },
  { name: "Kayole South", code: nil, constituency: nil },
  { name: "Komarock", code: nil, constituency: nil },
  { name: "Matopeni/Spring Valley", code: nil, constituency: nil },
  { name: "Upper Savannah", code: nil, constituency: nil },
  { name: "Lower Savannah", code: nil, constituency: nil },
  { name: "Embakasi", code: nil, constituency: nil },
  { name: "Utawala", code: nil, constituency: nil },
  { name: "Mihang'o", code: nil, constituency: nil },
  { name: "Umoja I", code: nil, constituency: nil },
  { name: "Umoja II", code: nil, constituency: nil },
  { name: "Mowlem", code: nil, constituency: nil },
  { name: "Kariobangi South", code: nil, constituency: nil },
  { name: "Maringo/Hamza", code: nil, constituency: nil },
  { name: "Viwandani", code: nil, constituency: nil },
  { name: "Harambee", code: nil, constituency: nil },
  { name: "Makongeni", code: nil, constituency: nil },
  { name: "Pumwani", code: nil, constituency: nil },
  { name: "Eastleigh North", code: nil, constituency: nil },
  { name: "Eastleigh South", code: nil, constituency: nil },
  { name: "Airbase", code: nil, constituency: nil },
  { name: "California", code: nil, constituency: nil },
  { name: "Nairobi Central", code: nil, constituency: nil },
  { name: "Pangani", code: nil, constituency: nil },
  { name: "Ziwani/Kariokor", code: nil, constituency: nil },
  { name: "Landimawe", code: nil, constituency: nil },
  { name: "Nairobi South", code: nil, constituency: nil },
  { name: "Hospital", code: nil, constituency: nil },
  { name: "Mabatini", code: nil, constituency: nil },
  { name: "Huruma", code: nil, constituency: nil },
  { name: "Ngei", code: nil, constituency: nil },
  { name: "Mlango Kubwa", code: nil, constituency: nil },
  { name: "Kiamaiko", code: nil, constituency: nil }
]