require "application_system_test_case"

class UserJourneyTest < ApplicationSystemTestCase
  test "user can sign up and submit an idea" do
    visit new_user_registration_path

    fill_in "user_username", with: "testuser"
    fill_in "user_email", with: "testuser@example.com"
    click_button "Sign up"

    # After sign up the app shows account links
    assert_text "Sign out"

    visit new_submission_path

    # Switch to the form tab if necessary
    if page.has_selector?("#tab-form")
      find("label[for='tab-form']").click
    end

    fill_in "submission_title", with: "Test idea from system test"
    fill_in "submission_description", with: "Short description generated by system test"

    # Select a valid sub-county and ward
    select "Westlands", from: "submission_sub_county"
    # Wait for wards to populate (JS) and pick first available ward
    using_wait_time 3 do
      if page.has_select?("submission_ward")
        select page.find("#submission_ward option:nth-child(2)").text, from: "submission_ward"
      end
    end
      # Choose a topic checkbox so validation passes
      check "Public Health Services"

    click_button "Submit My Idea"

    # The landing page may not show the flash in tests; assert the idea appears on the page
    assert_text "Test idea from system test"
  end
end
